"""Add precision and features columns to Model table

Revision ID: 897b02c65240
Revises: 
Create Date: 2024-09-23 17:51:05.026438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897b02c65240'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Model', sa.Column('precision', sa.Float(), nullable=True))
    op.add_column('Model', sa.Column('features', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Model', 'features')
    op.drop_column('Model', 'precision')
    # ### end Alembic commands ###
